---
- name: installation of epel-release
  yum: name=epel-release state=installed

- include: java.yaml

- name: adding tomcat group
  group: name=tomcat state=present

#- name: creating directory /opt/tomcat
#  file: path=/opt/tomcat state=directory

- name: creating the user for Apache tomcat
  user: name=tomcat shell=/bin/nologin group=tomcat createhome={{ home }}

- name: downloading tomcat
  get_url: url=http://www-us.apache.org/dist/tomcat/tomcat-8/v8.0.33/bin/apache-tomcat-8.0.33.tar.gz

- name: installing tomcat
  command: sudo tar -zxvf apache-tomcat-8.0.33.tar.gz -C /opt/tomcat --strip-components=1

- name: setting permissions
  file: 
    dest: /opt/tomcat/conf
    state: directory
    group: tomcat
    recursive: yes
    mode: "g+rwx"


  file:
    path: /opt/tomcat/conf/*
    usr: tomcat
    mode: "g+r"
    recursive: yes

- name: setting up systemd file for tomcat
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: starting apache tomcat
  service: name=tomcat state=started



